#!/usr/bin/env python3
"""
generate_4th_order.py
Generate 4th-order DSM coefficients
Spec: order=4, fs=2MHz, OSR=16, H_inf=4.0, opt=1, CIFF
"""

import sys
sys.path.insert(0, '/home/ubuntu/DSM_test/python-deltasigma-master')

from deltasigma import synthesizeNTF, realizeNTF
import numpy as np

# Specifications
order = 4
fs = 2e6
OSR = 16
H_inf = 4.0  # Note: High H_inf for 4th order
opt = 1  # optimized zeros
form = 'CIFF'

print("=" * 60)
print("4th-Order CIFF DSM Coefficient Generation")
print("=" * 60)
print(f"\nSpecifications:")
print(f"  Order: {order}")
print(f"  fs: {fs/1e6:.1f} MHz")
print(f"  OSR: {OSR}")
print(f"  Signal BW: {fs/(2*OSR)/1000:.1f} kHz")
print(f"  H_inf: {H_inf} (aggressive noise shaping)")
print(f"  opt: {opt} (optimized zeros)")
print(f"  Topology: {form}")

# Step 1: Synthesize NTF
print("\n[Step 1] Synthesize NTF")
ntf = synthesizeNTF(order, OSR, opt, H_inf, 0)
z, p, k = ntf

print(f"\nNTF:")
print(f"  Zeros: {len(z)} total")
for i, zi in enumerate(z):
    if np.iscomplex(zi):
        print(f"    z{i+1} = {zi.real:.6f} + j{zi.imag:.6f}")
    else:
        print(f"    z{i+1} = {zi:.6f}")

print(f"\n  Poles: {len(p)} total")
for i, pi in enumerate(p):
    if np.iscomplex(pi):
        print(f"    p{i+1} = {pi.real:.6f} + j{pi.imag:.6f}")
    else:
        print(f"    p{i+1} = {pi:.6f}")

print(f"\n  Gain: {k:.6f}")

# Step 2: Realize coefficients
print(f"\n[Step 2] Realize NTF ({form})")
a, g, b, c = realizeNTF(ntf, form)

print(f"\nCoefficients:")
print(f"  a = {a} (feedback)")
print(f"  g = {g} (resonator)")
print(f"  b = {b} (input)")
print(f"  c = {c} (inter-stage)")

# Step 3: Save to file
output_file = '/home/ubuntu/DSM_test/coefficients_4th_order.txt'

with open(output_file, 'w') as f:
    f.write(f"%% 4th-Order CIFF DSM Coefficients\n")
    f.write(f"%% order={order}, fs={fs/1e6}MHz, OSR={OSR}, H_inf={H_inf}, opt={opt}, form={form}\n")
    f.write(f"%% Generated by Python deltasigma\n\n")
    
    f.write(f"order = {order};\n")
    f.write(f"fs = {fs};\n")
    f.write(f"OSR = {OSR};\n")
    f.write(f"H_inf = {H_inf};\n\n")
    
    f.write(f"%% Feedback coefficients\n")
    f.write(f"a = [{' '.join([f'{x:.10f}' for x in a])}];\n\n")
    
    f.write(f"%% Resonator coefficients\n")
    if np.isscalar(g):
        f.write(f"g = [{g:.10f}];\n\n")
    else:
        g_list = np.atleast_1d(g)
        f.write(f"g = [{' '.join([f'{x:.10f}' for x in g_list])}];\n\n")
    
    f.write(f"%% Input coefficients\n")
    f.write(f"b = [{' '.join([f'{x:.10f}' for x in b])}];\n\n")
    
    f.write(f"%% Inter-stage coefficients\n")
    f.write(f"c = [{' '.join([f'{x:.10f}' for x in c])}];\n\n")

print(f"\n[Step 3] Saved to: {output_file}")
print("=" * 60)
print("Ready for Octave simulation!")
print("=" * 60)
